# Lu-Hf Decay
[<!-- module-htg badge --><span class="module module-htg">High-Temperature Geochemistry</span>](module-htg) 
```{index} Lu-Hf decay
```

In [8]:
# import relevant modules

import numpy as np
from math import log10, floor

In [9]:
# create our own functions

# function to round a value to a certain number of significant figures
def round_to_n_sf(value, no_of_significant_figures):
    value_rounded = round(value, no_of_significant_figures-1-int(floor(log10(abs(value)))))
    if value_rounded == int(value_rounded): 
        value_rounded = int(value_rounded)
    return value_rounded
            


## Lu-Hf Decay System

$${^{176}Lu \longrightarrow {^{176}Hf} + \beta^-} \qquad t_{\frac{1}{2}} = 36\,Gyr$$

The application of the $Lu$-$Hf$ isotope system was long hindered by analytical problems that were overcome by the introduction of a new mass spectrometric technique (termed MC-ICP-MS) in ~$1995$. As a result, the number of published $Hf$ isotope studies has greatly increased since then. 

An important remaining problem for the application of the $Hf$ isotope system for chronological studies is the uncertainty about the half-life of ${^{176}Lu}$. There is a discrepancy of about $4\%$ between recent results obtained from meteorites, terrestrial minerals, and direct counting experiments. This problem is the focus of ongoing investigations by a number of research groups. It also demonstrates that isotope geochemistry is research field, which still needs to resolve a number of basic but tricky problems. 

Lutetium ($Lu$) is a moderately incompatible heavy REE that occurs in dispersed form in nature. It forms the smallest trivalent ions of the REE and it is thus the most compatible REE during partial melting of the mantle. Important carrier phases of $Lu$ are garnet and zircon. Most rocks have $Lu$ concentration of less than $0.5\,ppm$.

Hafnium ($Hf$) is a high field strength element (HFSE) with an incompatibility similar to $Sm$. It generally occurs in dispersed form in rocks at concentrations of less than $10\,ppm$. Zirconium ($Zr$) and $Hf$ are geochemical twins, as they have the same ionic charge ($+4$) and (almost) the same ionic radius. As a consequence, zircon (if available) concentrates $Hf$ and has very low $Lu/Hf$ ratios.  

The $Lu$-$Hf$ system is most useful for dating mafic rocks, which have relatively high $Lu/Hf$ ratios. 

In [10]:
# Lu-Hf decay equation
# each return depends on what we want to find from the equation
def Lu_Hf_decay_equation(Hf176_Hf177_ratio, initial_Hf176_Hf177_ratio, Lu176_Hf177_ratio, t):
    decay_const_Lu = 1.94 * 10**-11  # yr^-1  # decay constant of Lu-176
    if Hf176_Hf177_ratio == '?':
        return initial_Hf176_Hf177_ratio + Lu176_Hf177_ratio*(np.exp(decay_const_Lu*t)-1)
    elif initial_Hf176_Hf177_ratio == '?':
        return Hf176_Hf177_ratio - Lu176_Hf177_ratio*(np.exp(decay_const_Lu*t)-1)
    elif Lu176_Hf177_ratio == '?':
        return (Hf176_Hf177_ratio - initial_Hf176_Hf177_ratio)/(np.exp(decay_const_Lu*t)-1)



## Problem Set 6 - Question 1

a) The Amitsoq Gneiss in Greenland crystallized $3.59\,Gyr$ ago with an initial ${^{176}Hf}/{^{177}Hf}$ of $0.280510$. Calculate the ${^{176}Lu}/{^{177}Hf}$ ratio of the magma source of the Amitsoq Gneiss, based on the assumption that it evolved from a reservoir that formed at $4.20\,Ga$ with a ${^{176}Hf}/{^{177}Hf}$ of $0.279900$.

b) Calculate the ${^{176}Hf}/{^{177}Hf}$ ratio of the bulk silicate Earth at $3.59\,Ga$, using the present-day values of $({^{176}Hf}/{^{177}Hf})_{Chon} = 0.282772$ and $({^{176}Lu}/{^{177}Hf})_{Chon} = 0.0334$.

c) With the data of (a) and the result of (b), calculate the initial $\epsilon_{Hf}$ value of the Amitsoq gneiss. What does this result and the ${^{176}Lu}/{^{177}Hf}$ ratio calculated above tell you?

<u>Solution</u>:

a) See below

In [11]:
# Question 1a

# Given values
Hf176_Hf177_ratio = 0.280510  # at t = 3.59 Gyr
initial_Hf176_Hf177_ratio = 0.279900  # at t = 4.20 Gyr
t = (4.20 - 3.59) * 10**9  # yr
# calculate Lu176/Hf177 ratio
Lu176_Hf177_ratio = Lu_Hf_decay_equation(Hf176_Hf177_ratio, initial_Hf176_Hf177_ratio, '?', t)
# print answer
print("The Lu-176/Hf-177 ratio of the magma source (3.59 Gya) of the Amitsoq Gneiss is %.4f." % Lu176_Hf177_ratio)

The Lu-176/Hf-177 ratio of the magma source (3.59 Gya) of the Amitsoq Gneiss is 0.0512.


As the distribution and evolution of $Lu$ and $Hf$ in the Earth are not explained in this page where we focus on quantitative parts, we will recall the concepts $\epsilon_{Hf}$ from the lecture slide before attempting questions b and c.

The $Hf$ isotope evolution of the BE and the BSE is relatively well defined (as for the $Sm$-$Nd$ system) because $Lu$ and $Hf$ are refractory and lithophile elements (like $Sm$ & $Nd$). The BE and BSE have an isotope evolution essentially identical to chondrites because they are characterized by a chondritic $Lu/Hf$ ratio.

When considering the $Hf$ isotope evolution of terrestrial reservoirs, it is thus useful to define an $\epsilon_{Hf}$ value, analogous to the commonly used $\epsilon_{Nd}$ notation:

$$\epsilon_{Hf} = \frac{({^{176}Hf}/{^{177}Hf}) - ({^{176}Hf}/{^{177}Hf})_{Chon}}{({^{176}Hf}/{^{177}Hf})_{Chon}} \times 10^4$$

where $({^{176}Hf}/{^{177}Hf})_{Chon} = 0.282772$. 

The $Hf$ isotope evolution of chondrites (and the BSE) is defined by the chondritic $Lu/Hf$ ratio of $({^{176}Lu}/{^{177}Hf})_{Chon} = 0.0334$

b) See below

In [12]:
# Question 1b

# Given values
Hf176_Hf177_ratio = 0.282772  # present-day
Lu176_Hf177_ratio = 0.0334  # present-day
t = 3.59 * 10**9  # yr
# calculate Hf176/Hf177 ratio at 3.59 Gya
initial_Hf176_Hf177_ratio = Lu_Hf_decay_equation(Hf176_Hf177_ratio, '?', Lu176_Hf177_ratio, t)  # at t = 3.59 Gyr
# print answer
print("The Hf-176/Hf-177 ratio of the BSE (3.59 Gya) is %g." % round_to_n_sf(initial_Hf176_Hf177_ratio, 6))

The Hf-176/Hf-177 ratio of the BSE (3.59 Gya) is 0.280363.


c) 

From a), the initial $Hf$ isotope ratio of the Amitsoq gneiss is $0.280510$.

From b), the initial $Hf$ isotope ratio of BSE (identical to Chondrite) is $0.280363$.

Calculate the initial value of $\epsilon_{Hf}$ (at $t=3.59\,Gyr$)

In [13]:
# function to calculate epsilon Nd
def epsilon_Hf(Hf_ratio_rock, Hf_ratio_Chon):
    return (Hf_ratio_rock - Hf_ratio_Chon)/Hf_ratio_Chon * 10000


# Question 1c

# Given values
initial_Hf_ratio_rock = 0.280510
initial_Hf_ratio_Chon = 0.280363
# print answer
print("The initial differences in Hf isotope compositions (relative to Chondrite) of the Amitsoq gneiss in parts per 10,000 is %g." \
      % round_to_n_sf(epsilon_Hf(initial_Hf_ratio_rock, initial_Hf_ratio_Chon), 3))

The initial differences in Hf isotope compositions (relative to Chondrite) of the Amitsoq gneiss in parts per 10,000 is 5.24.


The positive initial $\epsilon_{Hf}$ value indicates derivation from a depleted source, probably a depleted mantle. The ${^{176}Lu}/{^{177}Hf}$ ratio of the magma source is higher than the chondritic value of $0.0334$. This also indicates that the Amitsoq Gneiss was formed from a depleted source.

## References

- Lecture slide and Practical for Lecture 6 of the High-Temperature Geochemistry module